# type: ignore
import sys
from typing import Literal, List, Any, Optional, Tuple, Dict
import numpy as np
import enum
import numpy

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:ESKF2.h>    ####################

class Params:
    # process-noise std-devs

    sigma_an: float = 0.05  # /< 70ug/sqrt(hz)
    sigma_wn: float = 0.002  # /< rad/s white gyro noise
    sigma_aw: float = 0.0005  # /< 40ug m/s²/√s accelerometer random walk
    sigma_ww: float = 0.0001  # /< rad/s/√s gyro random walk

    init_cov: float = 1e-6
    def __init__(
        self,
        sigma_an: float = 0.05,
        sigma_wn: float = 0.002,
        sigma_aw: float = 0.0005,
        sigma_ww: float = 0.0001,
        init_cov: float = 1e-6,
    ) -> None:
        """Auto-generated default constructor with named params"""
        pass

class ESKF:
    g: Eigen.Vector3d  # (C++ static member) # (const)

    @overload
    def __init__(self) -> None:
        pass

    @overload
    def __init__(self, p: Params) -> None:
        pass

    def initialize(self) -> None:
        pass

    def get_quat(self) -> Vec4:
        pass

    def set_quat(self, coeffs: Vec4) -> None:
        pass

    def set_p(self, pp: Mat15) -> None:
        pass

    def predict(self, a_m: Vec3, w_m: Vec3, dt: float) -> None:
        pass

    def correct_zvup(self, rvv: Eigen.Matrix[float, 3, 3]) -> None:
        pass

    def correct_zvup_yvel(self, yvel: float, rvv: Eigen.Matrix[float, 3, 3]) -> None:
        pass

    def correct_zvup_projected(
        self, rvv: Eigen.Matrix[float, 3, 3], w_m: Eigen.Vector3d
    ) -> None:
        pass

    def correct_yaw(self, yaw_meas: float, rvv: float) -> None:
        pass

    def get_horizontal_vel(self) -> Tuple[float, float]:
        pass
    r_imu2ankle: Vec3

    x_: Vec3
    v_: Vec3
    q_: Quat
    a_b_: Vec3
    w_b_: Vec3
    p_: Mat15

    # debugging variables

    dbg_a_w_: Vec3
    dbg_yaw: float
    dbg_delta: Eigen.Vector[float, 15]

####################    </generated_from:ESKF2.h>    ####################

# </litgen_stub> // Autogenerated code end!
