                                                                                                                                                                                                                                  ; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = portenta_h7
build_dir = C:\.pio_build\folia_platio_filter_wb    ; Only needed for Windows compilation

[env]
upload_protocol = dfu
lib_deps =
  hideakitai/ArduinoEigen@^0.3.2
	nanopb/Nanopb@^0.4.91
	iq-motion-control/IQ Module Communication@^1.5.0

[env:portenta_h7]
framework     = arduino
platform      = ststm32
board         = portenta_h7_m7
build_flags   = 
  -O3 
  -LTO 
  -DARDUINO_ARCH_MBED 
  -DPORTENTA
  -DEI_CLASSIFIER_ENABLED
  -DEI_PORTING_ARDUINO=1
  -DEI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN=1
  -DARM_MATH_CM7
  -D__FPU_PRESENT=1
build_src_filter =
  +<*> -<bsp/unor4/> +<bsp/portenta/>

[env:native]
platform = native
build_flags =
    -std=c++11
    -D UNITY_INCLUDE_DOUBLE
lib_deps =
lib_extra_dirs = lib
lib_ldf_mode = deep+
lib_archive = no
build_src_filter =
    -<*>
test_filter = test_parseMTData2
